/**
 * Convex schema.
 *
 * `users` is keyed by Clerk's stable subject claim (`user_xxx`). The row
 * is JIT-created on first authenticated call (see `users.ensureProvisioned`).
 * Everything else (email, name, image) is mirrored from the Clerk identity
 * the first time we see the user; a future webhook can keep them in sync.
 *
 * `roles: string[]` is the only DB-side state for the ABAC system.
 * Role values are constrained to `Role` from `@enterprise-ai/shared` at
 * write time -- the schema can't declare a TS literal union directly
 * because Convex validators are runtime-only.
 *
 * Retail tables (`categories` ... `rollup_*`) hold synthetic data for a
 * fictional Mexican convenience-store chain. They're seeded by
 * `seedRetail.run` from JSON fixtures generated by
 * `scripts/generate-fixtures.ts`. Aggregations the LLM tool DSL serves
 * hit the `rollup_*` tables; raw tables are reserved for drill-downs.
 * See `.cursor/plans/mexican_retail_synthetic_seed_*.plan.md`.
 */

import { defineSchema, defineTable } from 'convex/server'
import { v } from 'convex/values'

export default defineSchema({
  users: defineTable({
    // Clerk's `sub` claim, e.g. `user_2abcXYZ`. Stable across sessions.
    subject: v.string(),
    email: v.optional(v.string()),
    name: v.optional(v.string()),
    image: v.optional(v.string()),
    roles: v.array(v.string()),
  })
    .index('by_subject', ['subject'])
    .index('email', ['email']),

  prompts: defineTable({
    authorId: v.id('users'),
    title: v.string(),
    body: v.string(),
    archived: v.boolean(),
  }).index('by_author', ['authorId']),

  // ---- Retail: raw tables ------------------------------------------------

  categories: defineTable({
    slug: v.string(),
    name_es: v.string(),
    sortOrder: v.number(),
  }).index('by_slug', ['slug']),

  products: defineTable({
    sku: v.string(),
    name_es: v.string(),
    categoryId: v.id('categories'),
    priceMxn: v.number(),
    costMxn: v.number(),
    isActive: v.boolean(),
  })
    .index('by_sku', ['sku'])
    .index('by_category', ['categoryId']),

  stores: defineTable({
    code: v.string(),
    name_es: v.string(),
    city: v.string(),
    region: v.string(),
    openedAt: v.number(),
  })
    .index('by_code', ['code'])
    .index('by_region', ['region']),

  customers: defineTable({
    loyaltyId: v.string(),
    signupAt: v.number(),
    city: v.string(),
    segment: v.union(
      v.literal('frequent'),
      v.literal('occasional'),
      v.literal('new'),
    ),
  }).index('by_loyaltyId', ['loyaltyId']),

  transactions: defineTable({
    storeId: v.id('stores'),
    customerId: v.optional(v.id('customers')),
    occurredAt: v.number(),
    totalMxn: v.number(),
    kind: v.union(
      v.literal('sale'),
      v.literal('service'),
      v.literal('return'),
    ),
    serviceType: v.optional(
      v.union(
        v.literal('recarga'),
        v.literal('pago_servicio'),
        v.literal('transferencia'),
        v.literal('loteria'),
      ),
    ),
    promoId: v.optional(v.id('promotions')),
  })
    .index('by_store_time', ['storeId', 'occurredAt'])
    .index('by_time', ['occurredAt'])
    .index('by_kind_time', ['kind', 'occurredAt']),

  // `occurredAt` is denormalized here so product time-series queries
  // (e.g. monthly product revenue) don't need a join into `transactions`.
  transaction_items: defineTable({
    transactionId: v.id('transactions'),
    productId: v.id('products'),
    quantity: v.number(),
    unitPriceMxn: v.number(),
    discountMxn: v.number(),
    occurredAt: v.number(),
  })
    .index('by_transaction', ['transactionId'])
    .index('by_product_time', ['productId', 'occurredAt']),

  inventory_movements: defineTable({
    storeId: v.id('stores'),
    productId: v.id('products'),
    occurredAt: v.number(),
    kind: v.union(
      v.literal('restock'),
      v.literal('sale'),
      v.literal('stockout_start'),
      v.literal('stockout_end'),
    ),
    quantity: v.number(),
  }).index('by_store_product_time', ['storeId', 'productId', 'occurredAt']),

  promotions: defineTable({
    code: v.string(),
    name_es: v.string(),
    startAt: v.number(),
    endAt: v.number(),
    discountPct: v.number(),
    scopeCategoryId: v.optional(v.id('categories')),
  }).index('by_time', ['startAt']),

  // ---- Retail: rollup tables (precomputed in the generator) --------------
  //
  // Every analytical question the LLM tool DSL serves should hit one of
  // these; raw tables are reserved for drill-downs. Rollups are emitted
  // as JSON by the generator so the seed action stays a dumb loader.

  rollup_daily_store_sales: defineTable({
    storeId: v.id('stores'),
    dateKey: v.string(), // YYYY-MM-DD
    revenueMxn: v.number(),
    transactions: v.number(),
    units: v.number(),
  }).index('by_store_date', ['storeId', 'dateKey']),

  rollup_daily_store_category_sales: defineTable({
    storeId: v.id('stores'),
    categoryId: v.id('categories'),
    dateKey: v.string(),
    revenueMxn: v.number(),
    units: v.number(),
  }).index('by_store_category_date', ['storeId', 'categoryId', 'dateKey']),

  // Aggregated across the full 18 months -- one row per
  // (store, dayOfWeek, hour). Keeps the heatmap query O(168 * stores).
  rollup_hourly_store_sales: defineTable({
    storeId: v.id('stores'),
    dayOfWeek: v.number(), // 0=Sun .. 6=Sat
    hour: v.number(), // 0..23
    avgRevenueMxn: v.number(),
    avgTransactions: v.number(),
  }).index('by_store_dow_hour', ['storeId', 'dayOfWeek', 'hour']),

  rollup_product_monthly: defineTable({
    productId: v.id('products'),
    monthKey: v.string(), // YYYY-MM
    revenueMxn: v.number(),
    units: v.number(),
  }).index('by_product_month', ['productId', 'monthKey']),

  rollup_services_monthly: defineTable({
    monthKey: v.string(),
    serviceType: v.union(
      v.literal('recarga'),
      v.literal('pago_servicio'),
      v.literal('transferencia'),
      v.literal('loteria'),
    ),
    revenueMxn: v.number(),
    transactions: v.number(),
  }).index('by_month_service', ['monthKey', 'serviceType']),

  rollup_geo_monthly: defineTable({
    region: v.string(),
    monthKey: v.string(),
    revenueMxn: v.number(),
    transactions: v.number(),
    avgTicketMxn: v.number(),
  }).index('by_region_month', ['region', 'monthKey']),
})
